### ISSUE TITLE
Неверное количество оборудования

### ISSUE THREAD

**Issue by DmitryKolesov** [kirik8008/TheTeachersKit#1]
@kirik8008, при добавлении оборудования **с инв.номерами** какие то непонятные числа считает)) Исправь!))
> /device/all
ячейка "Количество"

+ И когда пустая база идет поиск дубликатов ИНВ.номеров... - это как то не очень(

**Comment by kirik8008** [comment]
@DmitryKolesov, да про первую ошибку знаю и уже исправил в локальном. А вот про поиск дубликатов не видел, исправлю!
