### ISSUE TITLE
Отображение аватарки из skype

### ISSUE THREAD

**Issue by DmitryKolesov** [kirik8008/TheTeachersKit#2]
@kirik8008, ну это опять я))
После последнего обновления, в котором появилась возможность добавлять аватарки из skype... - это не совсем практично, так как у некоторых фотка есть, а тут она не отображается (т.е синий экранчик), ну это я думаю в настройках конфиденциальности самого skype.
**Первое** что я заметил - это когда редактируешь пользователя, там есть checkbox "Использовать вместо данной аватарки, фото из skype" так вот, если его выбрать то фотка не загружается, а если снять и заново поставить, то фотка появляется.
**Второе** - по важнее. Если фотка у пользователя менялась, то при использовании поиска, фотку пользователя не находит и выдает файл типа: "/graphics/photo/1".
**Третье !** - Если пользователь был удален - история не очищается! То есть если создается новый пользователь и у него появляется история совсем другого человека...

**Comment by kirik8008** [comment]
Спасибо Дима за информацию! В ближайшее время думаю разберусь😉!

**Comment by kirik8008** [comment]
С задержкой, но исправлено!
